version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres/data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    depends_on:
      - postgres
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    links:
      - postgres
    command: npm run start:dev
volumes:
  db:
    driver: local